name              'sc-chruby'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs and configures chruby'
version           '0.1.2'
source_url        'https://github.com/sous-chefs/sc-chruby'
issues_url        'https://github.com/sous-chefs/sc-chruby/issues'
chef_version      '>= 14.0'

supports 'debian'
supports 'ubuntu'
supports 'centos'
supports 'redhat'
supports 'oracle'
supports 'amazon'
supports 'mac_os_x'
