name              'chruby'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs and configures chruby'
long_description  IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version           '0.0.1'
source_url        'https://github.com/sous-chefs/chruby'
issues_url        'https://github.com/sous-chefs/chruby/issues'
chef_version      '>= 14.0'

supports 'debian'
supports 'ubuntu'
supports 'centos'
supports 'redhat'
supports 'oracle'
supports 'amazon'
supports 'macos'
